[package]
name = "crypto"
version = "0.1.0"
authors = ["Joaquin L. Pereyra <joaquinlpereyra@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.10.1"
